### ISSUE TITLE
Use Async (Sync) Cache Api to get cache content

### ISSUE THREAD

**Issue by felipebonezi** [thibaultmeyer/play-redis-module#6]
One of the best things we have in Play is the interface to implement our own Cache Api.
I think we can leverage this advantage to use this Redis Module over Async/Sync Cache Api.

https://www.playframework.com/documentation/2.8.x/JavaCache
https://www.playframework.com/documentation/2.8.x/ScalaCache

**Comment by thibaultmeyer** [comment]
Hello,

that's a good idea. I think the implementation of AsyncCacheApi can directly use the PlayRedis class itself.

**Comment by felipebonezi** [comment]
@thibaultmeyer any idea how to implement `AsyncCacheApi`?
I didn't saw any implementation using a non-blocking process on `PlayRedisImpl`.

**Comment by thibaultmeyer** [comment]
@felipebonezi Jedis does not support Async operations. You can simulate it by using `CompletableFuture`


```java
public class AsyncCaheRedisImpl implements AsyncCacheApi {

    private final PlayRedis playRedis;

    /**
     * Build a new instance.
     *
     * @param playRedis The PlayRedis module instance
     * @since 05.10.20
     */
    @Inject
    public AsyncCaheRedisImpl (final PlayRedis playRedis) {
        this.playRedis = playRedis;
    }

    @Override
    public <T> CompletionStage<Optional<T>> get(final String s) {
        return CompletableFuture.supplyAsync(() ->
            Optional.ofNullable(playRedis.get(s, new TypeReference<T>() {
            }))
        );
    }
}
```
